/** Declaration file generated by dts-gen */

import { Model } from "ui-data";
import JQuery from 'jquery';

type mainFn = (scope: any, view: fn.View) => void;
type registerFn = (scope: any) => void;

export const config: {
    singlePageBaseUrl: string;
    singlePageViewParent: string;
    tabIndexAttributeName: string;
    uiNameAttributeName: string;
    viewIndexAttributeName: string;
    viewStatusAttributeName: string;
    viewUrlAttributeName: string;
    viewTitleAttributeName: string;
    viewLoadedAttributeName: string;
    viewNameAttributeName: string;
};

export const messages: {
    notFoundFullUrl: string;
    notFoundUrlPattern: string;
    notFoundviewName: string;
    unknownError: string;
};

export const constants: {
  VIEW_LOADED_TRUE: string;
  VIEW_LOADED_FALSE: string;
  VIEW_LOADED_ERROR: string;
  VIEW_STATUS_INIT: string;
  VIEW_STATUS_READY: string;
  VIEW_STATUS_SHOW: string;
  VIEW_STATUS_HIDDEN: string;
  VIEW_STATUS_DESTROY: string;
};

export function app(): void;

export function utils(): void;

export namespace app {

    /**
     * @description 加载视图
     * @param {string} url URL字符串
     */
    function loadView(url: any): void;

    /**
     * @description 替换视图
     * @param {string} url URL字符串
     */
    function replaceView(url: any): void;

    /**
     * @description 返回到之前的视图
     * @param {string} url URL字符串
     */
    function popView(url: any): void;

    /**
     * @description 加载视图并添加到堆栈顶部
     * @param {string} url URL字符串
     */
    function pushView(url: any): void;

    /**
     * @description 显示错误信息
     * @param {string} message 
     */
    function showError(message: any): void;

    /**
     * @description 显示信息
     * @param {string} message 
     */
    function showMessage(message: any): void;

    /**
     * @description 注册视图主函数
     * @param {string} viewName 
     * @param {function} mainFn 
     */
    function viewMain(viewName: any, mainFn: mainFn): void;

    /**
     * @description 初始视图作用域
     * @param {string} viewName 
     * @param {function} registerFn 
     */
    function viewScope(viewName: any, registerFn: registerFn): void;

}

export namespace fn {
    class AjaxCallService {
        constructor(sourceElement: any);

        beforeSend(jqXHR: any, settings: any): void;

        callService(url: any, data: any, opts: any): AjaxResult;

        convertData(data: any, opts: any): any;
    }

    class AjaxResult {
        constructor(deferred: any, sourceElement: any);

        doHandleResult(doneFn: any, failFn: any, showMask: any): AjaxResult;

        thenResult(doneFn: any, failFn: any): AjaxResult;

        waitResult(doneFn: any, failFn: any): AjaxResult;

        static handleAjaxError(sourceElement: any, jqXHR: any, textStatus: any, errorThrown: any): void;

    }

    class SequenceGenerator {
        constructor(initValue: any, ...args: any[]);

        nextValue(): any;

    }

    class View {
        constructor(viewElement: any, viewInfo: any, viewScope: any);

        $find(...args: any[]): JQuery;

        $ui(name: any): JQuery;

        callService(url: any, data: any, opts: any): AjaxResult;

        getDataModel(): Model;

        getUrlParam(name: any): any;

        getUrlParams(): any;

        getViewElement(): any;

        getViewInfo(): ViewInfo;

        getViewScope(): any;

    }

    class ViewInfo {
        constructor();

        getFullUrl(): any;

        getUrlPattern(): any;

        getViewName(): any;

        setFullUrl(fullUrl: any): void;

        setUrlPattern(urlPattern: any): void;

        setViewName(viewName: any): void;

    }

    class LoadedViewHolder {
        constructor(loadedView: any);

        getViewObject(): View;

        getViewScope(): any;

        setViewToShow(): void;

        setViewToHide(): void;

        getViewScopePropValue(propName: any): any;

        setViewScopePropValue(propName: any, propValue: any): void;

        getDomElementAttrValue(attrName: any): any;

        setDomElementAttrValue(attrName: any, attrValue: any): void;
    }

    class ViewLoader {
        constructor(targetElement: any, callbackFn: any);

        initViewAfterRender(): void;

        loadView(url: any): void;

        preRenderView(url: any, data: any, textStatus: any, jqXHR: any): boolean;

        renderView(url: any, data: any, textStatus: any, jqXHR: any): void;

        static lastViewInfo: {
        };

    }

    class ViewMask {
        constructor(viewElement: any);

        hiddenMask(): void;

        showMask(): void;

    }

    class ViewResponse {
        constructor(url: any, jqXHR: any);

        getViewInfo(): ViewInfo;

    }

    function Ajax(): void;

    function App(): void;

    function AppAlertMessages(): void;

    function BrowserUrl(): void;

    function BrowserTitle(): void;

    function Global(): void;

    function UrlParser(): void;

    function Utils(): void;

    function ViewManager(): void;

    function ViewScopeManager(): void;

    namespace Ajax {
        function callService(url: any, data: any, opts: any): AjaxResult;

    }

    namespace App {
        function loadView(url: any): void;

        function replaceView(url: any): void;

        function popView(url: any): void;

        function pushView(url: any): void;

        function showError(message: any): void;

        function showMessage(message: any): void;

        function viewMain(viewName: any, mainFn: mainFn): void;

        function viewScope(viewName: any, registerFn: registerFn): void;

    }

    namespace AppAlertMessages {
        function showError(message: any): void;

        function showMessage(message: any): void;

    }

    namespace BrowserUrl {
        function getBrowserUrl(viewUrl: any): any;

        function getFullUrl(relativeUrl: any): any;

        function setBrowserUrl(viewUrl: any): void;

        function setLocationUrl(newUrl: any): void;

    }

    namespace BrowserUrl {

        function setBrowserTitle(viewTitle: any): void;

    }

    namespace Global {
        const config: {
            singlePageBaseUrl: string;
            singlePageViewParent: string;
            tabIndexAttributeName: string;
            uiNameAttributeName: string;
            viewIndexAttributeName: string;
            viewStatusAttributeName: string;
            viewUrlAttributeName: string;
            viewTitleAttributeName: string;
            viewLoadedAttributeName: string;
            viewNameAttributeName: string;
        };

        const messages: {
            notFoundFullUrl: string;
            notFoundUrlPattern: string;
            notFoundviewName: string;
            unknownError: string;
        };

        const constants: {
            VIEW_LOADED_TRUE: string;
            VIEW_LOADED_FALSE: string;
            VIEW_LOADED_ERROR: string;
            VIEW_STATUS_INIT: string;
            VIEW_STATUS_READY: string;
            VIEW_STATUS_SHOW: string;
            VIEW_STATUS_HIDDEN: string;
            VIEW_STATUS_DESTROY: string;
        };

    }

    namespace UrlParser {
        function parseAllParams(fullUrl: any, urlPattern: any): any;

        function parsePathParams(fullUrl: any, urlPattern: any): any;

        function parseQueryParams(fullUrl: any): any;

    }

    namespace Utils {
        function concatObjects(...objectArray: any[]): any;

        function concatObjectsWithOption(skipUndefinedProperties: boolean, ...objectArray: any[]): any;

        function convertToString(arg: any): any;

        function emptyArrayIfNullOrUndefined(arg: any): any;

        function emptyObjectIfNullOrUndefined(arg: any): any;

        function emptyStringIfNullOrUndefined(arg: any): any;

        function formatString(format: any, ...objectArray: any[]): any;

        function isFunction(arg: any): any;

        function isNotEmptyObject(arg: any): any;

        function isNotEmptyString(arg: any): any;

        function isNullOrUndefined(arg: any): any;

        function isNumber(arg: any): any;

        function isObject(arg: any): any;

        function isString(arg: any): any;

    }

    namespace ViewLoader {
        namespace elementIdSuffixGenerator {
            function nextValue(): any;

        }

        namespace viewIndexSuffixGenerator {
            function nextValue(): any;

        }

    }

    namespace ViewManager {

        const currentTab: {
            tabIndex: string;
        };

        function stopViewLifecycle(viewElement: any): void;

        function doRenderView(url: any, afterRenderFn: any): void;

        function startViewLifecycle(viewElement: any): void;

        function loadView(url: any): void;

        function replaceView(url: any): void;

        function hiddenView(viewElement: any): void;

        function popView(url: any): void;

        function pushView(url: any): void;

        function showView(viewElement: any): void;

    }

    namespace ViewScopeManager {

        const viewScopes: {
        };

        function getViewScope(viewName: any, allowCreate: boolean): any;

        function removeViewScope(viewName: any): void;

        function setViewScope(viewName: any, viewScope: any): void;

    }

}

export namespace utils {
    function concatObjects(...objectArray: any[]): any;

    function concatObjectsWithOption(skipUndefinedProperties: boolean, ...objectArray: any[]): any;

    function convertToString(arg: any): any;

    function emptyArrayIfNullOrUndefined(arg: any): any;

    function emptyObjectIfNullOrUndefined(arg: any): any;

    function emptyStringIfNullOrUndefined(arg: any): any;

    function formatString(format: any, ...objectArray: any[]): any;

    function isFunction(arg: any): any;

    function isNotEmptyObject(arg: any): any;

    function isNotEmptyString(arg: any): any;

    function isNullOrUndefined(arg: any): any;

    function isNumber(arg: any): any;

    function isObject(arg: any): any;

    function isString(arg: any): any;

}

